-- 预置数据：基础词书与单词

INSERT INTO wordbooks (id, name, name_en, level, word_count, sort_order)
VALUES (1, '基础词汇', 'Basic Vocabulary', 'beginner', 20, 1),
       (2, '进阶词汇', 'Advanced Vocabulary', 'intermediate', 20, 2)
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO words (id, wordbook_id, indonesian, chinese, english, example_indonesian, example_zh, example_en,
                   sort_order)
VALUES (1, 1, 'Apel', '苹果', 'Apple', 'Saya suka makan apel.', '我喜欢吃苹果。', 'I like to eat apples.', 1),
       (2, 1, 'Buku', '书', 'Book', 'Saya membaca buku setiap hari.', '我每天读书。', 'I read books every day.', 2),
       (3, 1, 'Air', '水', 'Water', 'Minum air putih lebih sehat.', '喝白开水更健康。',
        'Drinking plain water is healthier.', 3),
       (4, 1, 'Rumah', '房子', 'House', 'Rumah saya besar dan nyaman.', '我的房子又大又舒适。',
        'My house is big and comfortable.', 4),
       (5, 1, 'Kucing', '猫', 'Cat', 'Kucing saya suka tidur di sofa.', '我的猫喜欢在沙发上睡觉。',
        'My cat likes to sleep on the sofa.', 5),
       (6, 1, 'Anjing', '狗', 'Dog', 'Anjing itu setia pada tuannya.', '那只狗对主人很忠诚。',
        'That dog is loyal to its owner.', 6),
       (7, 1, 'Mobil', '汽车', 'Car', 'Ayah saya mengendarai mobil ke kantor.', '我爸爸开车去上班。',
        'My father drives a car to work.', 7),
       (8, 1, 'Sepeda', '自行车', 'Bicycle', 'Saya bersepeda ke sekolah.', '我骑自行车去学校。',
        'I ride a bicycle to school.', 8),
       (9, 1, 'Makan', '吃', 'Eat', 'Mari makan bersama!', '一起吃饭吧！', 'Let us eat together!', 9),
       (10, 1, 'Minum', '喝', 'Drink', 'Dia minum kopi setiap pagi.', '他每天早上喝咖啡。',
        'He drinks coffee every morning.', 10),
       (11, 1, 'Tidur', '睡觉', 'Sleep', 'Anak-anak perlu tidur delapan jam.', '孩子们需要睡八个小时。',
        'Children need to sleep eight hours.', 11),
       (12, 1, 'Bangun', '起床', 'Wake up', 'Saya bangun pukul enam pagi.', '我早上六点起床。',
        'I wake up at six in the morning.', 12),
       (13, 1, 'Sekolah', '学校', 'School', 'Murid-murid belajar di sekolah.', '学生们在学校学习。',
        'Students study at school.', 13),
       (14, 1, 'Guru', '老师', 'Teacher', 'Guru kami sangat baik.', '我们的老师非常好。', 'Our teacher is very kind.',
        14),
       (15, 1, 'Teman', '朋友', 'Friend', 'Dia adalah teman baik saya.', '他是我的好朋友。', 'He is my good friend.',
        15),
       (16, 1, 'Keluarga', '家庭', 'Family', 'Keluarga saya tinggal di Jakarta.', '我的家庭住在雅加达。',
        'My family lives in Jakarta.', 16),
       (17, 1, 'Ibu', '妈妈', 'Mother', 'Ibu sedang memasak di dapur.', '妈妈正在厨房做饭。',
        'Mother is cooking in the kitchen.', 17),
       (18, 1, 'Ayah', '爸爸', 'Father', 'Ayah bekerja sebagai dokter.', '爸爸从事医生工作。',
        'Father works as a doctor.', 18),
       (19, 1, 'Panas', '热', 'Hot', 'Hari ini sangat panas.', '今天非常热。', 'Today is very hot.', 19),
       (20, 1, 'Dingin', '冷', 'Cold', 'Malam ini terasa dingin.', '今晚感觉很冷。', 'Tonight feels cold.', 20),

       (21, 2, 'Perjalanan', '旅行', 'Journey', 'Perjalanan ke Bali sangat menyenangkan.', '去巴厘岛的旅行非常愉快。',
        'The journey to Bali was very enjoyable.', 1),
       (22, 2, 'Pengalaman', '经验', 'Experience', 'Dia punya banyak pengalaman kerja.', '他有很多工作经验。',
        'He has a lot of work experience.', 2),
       (23, 2, 'Kebudayaan', '文化', 'Culture', 'Indonesia memiliki kebudayaan yang kaya.', '印尼拥有丰富的文化。',
        'Indonesia has a rich culture.', 3),
       (24, 2, 'Pendidikan', '教育', 'Education', 'Pendidikan sangat penting bagi masa depan.', '教育对未来非常重要。',
        'Education is very important for the future.', 4),
       (25, 2, 'Kesehatan', '健康', 'Health', 'Kesehatan lebih berharga dari kekayaan.', '健康比财富更宝贵。',
        'Health is more valuable than wealth.', 5),
       (26, 2, 'Lingkungan', '环境', 'Environment', 'Kita harus menjaga lingkungan.', '我们必须保护环境。',
        'We must protect the environment.', 6),
       (27, 2, 'Teknologi', '技术', 'Technology', 'Teknologi berkembang sangat cepat.', '技术发展非常迅速。',
        'Technology is developing very rapidly.', 7),
       (28, 2, 'Ekonomi', '经济', 'Economy', 'Ekonomi negara sedang membaik.', '国家经济正在好转。',
        'The national economy is improving.', 8),
       (29, 2, 'Politik', '政治', 'Politics', 'Politik di Indonesia sangat dinamis.', '印尼的政治非常活跃。',
        'Politics in Indonesia is very dynamic.', 9),
       (30, 2, 'Sejarah', '历史', 'History', 'Kita harus belajar dari sejarah.', '我们必须从历史中学习。',
        'We must learn from history.', 10),
       (31, 2, 'Seni', '艺术', 'Art', 'Seni tradisional Indonesia sangat indah.', '印尼传统艺术非常美丽。',
        'Indonesian traditional art is very beautiful.', 11),
       (32, 2, 'Bahasa', '语言', 'Language', 'Belajar bahasa asing sangat berguna.', '学习外语非常有用。',
        'Learning a foreign language is very useful.', 12),
       (33, 2, 'Agama', '宗教', 'Religion', 'Indonesia menganut banyak agama.', '印尼信奉多种宗教。',
        'Indonesia adheres to many religions.', 13),
       (34, 2, 'Pekerjaan', '工作', 'Job', 'Dia mencari pekerjaan yang baru.', '他在找一份新工作。',
        'He is looking for a new job.', 14),
       (35, 2, 'Pertanian', '农业', 'Agriculture', 'Pertanian adalah sektor penting.', '农业是重要的产业。',
        'Agriculture is an important sector.', 15),
       (36, 2, 'Industri', '工业', 'Industry', 'Industri manufaktur tumbuh pesat.', '制造业发展迅速。',
        'The manufacturing industry is growing rapidly.', 16),
       (37, 2, 'Pariwisata', '旅游', 'Tourism', 'Pariwisata Bali terkenal di dunia.', '巴厘岛旅游业世界闻名。',
        'Bali tourism is world-famous.', 17),
       (38, 2, 'Transportasi', '交通', 'Transportation', 'Transportasi umum di Jakarta sangat ramai.',
        '雅加达的公共交通非常繁忙。', 'Public transportation in Jakarta is very busy.', 18),
       (39, 2, 'Komunikasi', '交流', 'Communication', 'Komunikasi yang baik penting dalam tim.',
        '良好的交流在团队中很重要。', 'Good communication is important in a team.', 19),
       (40, 2, 'Masyarakat', '社会', 'Society', 'Kita hidup dalam masyarakat yang majemuk.', '我们生活在多元社会中。',
        'We live in a pluralistic society.', 20)
ON DUPLICATE KEY UPDATE indonesian = indonesian;
